### ISSUE TITLE
Spurious newlines before bullet list item

### ISSUE THREAD

**Issue by clach04** [mattharrison/rst2odp#13]
Slide like:

    Problem slide
    =============

    List 1

    *   item 1
    *   item 2
    *   item 3

    List 2

    *   item 1, too many newlines above

Ends up with spurious newlines before the last bullet.

Full test:

    =====================
    too many newlines bug
    =====================

    Too many newslines before last bullet

    To build::

        rst2odp.py bug_spurious_newlines.txt bug_spurious_newlines_odp.odp

    Problem slide
    =============

    List 1

    *   item 1
    *   item 2
    *   item 3

    List 2

    *   item 1, too many newlines above

**Comment by mattharrison** [comment]
This works in 0.3.1
