### ISSUE TITLE
image scale fail

### ISSUE THREAD

**Issue by Thomas-Tsai** [mattharrison/rst2odp#26]
hello,

thank you for this project, it's helpful for me.

there are one question about image scale. give scale option will make image display empty. i can't scale image, image just disappear.
eg:
.. image:: img/test.png
        :scale: 150 %
run:
rst2odp intro.rst intro.odp
open the intro.odp and image is empty.

any idea ?
thank you!

**Comment by mattharrison** [comment]
Updated intro.rst with examples of image placement. Scale is not supported, but you can fill to a grid.
