### ISSUE TITLE
Query: can it use sphinx based document also as source , instead of plain simple docutils based document?

### ISSUE THREAD

**Issue by zaxebo1** [mattharrison/rst2odp#31]
I need to use a particular "sphinx extension" in my document. So my rst is sphinx compatible rst, not just plain simple docutils rst.
(Say this extension which i am using in my document is "plantuml" from the list of sphinx extensions given at https://bitbucket.org/birkenfeld/sphinx-contrib/src/    .It can be sometimes "nwdiag" sphinx extension also )

**Now, can i somehow use rst2odp to generate odp from sphinx compatible rst?** 

====

For example , i currently use "hieroglyph"
https://github.com/nyergler/hieroglyph/blob/master/docs/getting-started.rst
https://pypi.python.org/pypi/hieroglyph
Hieroglyph is an extension for Sphinx which builds HTML presentations from sphinx based ReStructured Text documents. 

**Very importantly, We can use any sphinx extension based directives in hieroglyph based presentations, because "hieroglyph" is itself a sphinx extension (important to refer: "Sphinx Extensions" section in https://github.com/nyergler/hieroglyph/blob/master/docs/getting-started.rst )**

The only problem with Hieroglyph is that it does not produces "odp", it generates html browser based presentations.

====

**Now, can i somehow use the rst2odp to "generate odp" from sphinx extensions compatible rst document?**  (and not just only plain docutils rst document)

**Comment by mattharrison** [comment]
Hi, you can try and feed it sphinx content, but I'm pretty sure it will choke. I don't have much interest in supporting Sphinx extensions, but would accept patches.

**Comment by zaxebo1** [comment]
I can write sphinx extensions itself.
but regarding rstodp eating sphinx document, can (if possible) you  "atleast point"  me some algorithmicly step-wise path as to how it can be done, I will be happy to implement it.

**Comment by mattharrison** [comment]
Do you have a minimal example you could upload? To really support Sphinx, you need to go from the Sphinx side and subclass my code. Going from docutil to support sphinx is really the wrong way. (Trust me I have tried to support Sphinx in my rst2epub2 and rst2nitrile)

**Comment by zaxebo1** [comment]
ok, i will try from sphinx side only
