### ISSUE TITLE
Autocompletition of template file

### ISSUE THREAD

**Issue by Fale** [mattharrison/rst2odp#37]
I have a `Fedora_Slide_Deck_16x10.otp` template in the current folder.

If I write
````
rst2odp --template-file=Fedora
````
and use TAB, it is not able to auto-complete. I think it's an option to specify to make bash know that it can autocomplete with file names

**Comment by mattharrison** [comment]
This is a bash issue. Use a space instead of ``=`` and you will get tab completion.
