### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Fale** [mattharrison/rst2odp#40]
The LICENSE file seems to be MIT (https://opensource.org/licenses/MIT), while the setup.py affirms that it's Apache licensed. Which one is right?

**Comment by Fale** [comment]
From https://github.com/mattharrison/rst2odp/commit/dc2e651aac6ed2bd25437dd49fdbdc678fce3ebc seems like it was Apache and got modified to MIT

**Comment by mattharrison** [comment]
I decided to switch to MIT.

**Comment by mattharrison** [comment]
updated setup.py
