### ISSUE TITLE
How does vertical spacing work with document info / attributes block?

### ISSUE THREAD

**Issue by mattharrison** [mattharrison/rst2odp#42]
From a user @agapow :

* Looking at the document info / attributes block, rst2odp prints all of them on the title slide. However, I can't work out

- how vertical spacing occurs. I've got name, organisation, date, email, twitter handle (in that order) and it appears name (space) organisation, date (space) email, twitter

**Comment by mattharrison** [comment]
If you want to get me a sample rst, I could look into this.

**Comment by agapow** [comment]
Example attached - linebreaks seem to happen after the author and the date fields

[fields-spacing-1.txt](https://github.com/mattharrison/rst2odp/files/1919986/fields-spacing-1.txt)
