### ISSUE TITLE
Allow ElementTree to be an older version

### ISSUE THREAD

**Issue by clach04** [mattharrison/rst2odp#9]
Older versions of Python do not include ElementTree. Here is a patch (rather than a pull request) for support for older versions:

    diff --git a/bin/rst2odp b/bin/rst2odp
    diff --git a/odplib/preso.py b/odplib/preso.py
    index 408c9ce..d870084 100644
    --- a/odplib/preso.py
    +++ b/odplib/preso.py
    @@ -9,7 +9,10 @@ Licensed under Apache License, Version 2.0 (current)

     import copy
     import cStringIO as sio
    -import xml.etree.ElementTree as et
    +try:
    +    import xml.etree.ElementTree as et
    +except ImportError:
    +    from elementtree import ElementTree as et
     from xml.dom import minidom
     import os
     import sys

**Comment by mattharrison** [comment]
We know require lxml
